### ISSUE TITLE
Loadbalancing / HA Proxy

### ISSUE THREAD

**Issue by RalphK83** [privacyidea/adfs-provider#14]
We are using 3 PI Servers and 1 Database with HA Proxy.

We have the following User / Token process: User does not have indexed secret token -> User is doing ADFS Authentication (Username/Password)-> PI is creating via script the indexed secret token “on the fly” in the background -> User can login within the same ADFS Authentication Session with the indexed secret token.

Now with the HAProxy: Indexed secret token is created in the background, but User cannot use the token in the same ADFS “Session”. _Maybe_ ADFS PrivacyIdea Provider is not handling persistent Session Cookies?

Thanks

**Comment by cornelinux** [comment]
@RalphK83  I think this is not related to the ADFS plugin. 

I think it is a handler configuration issue on the server, so that the event handler could be a post-handler.
We also added a checkbox in regards to the database sync in the handlers.

@nilsbehlen I would recommend to close this.
