### ISSUE TITLE
Can you build new version msi? (With Enable TOTP Token Enrollment)

### ISSUE THREAD

**Issue by arpsyapathy** [privacyidea/adfs-provider#18]
Hi all!

Can you build new version msi? (With Enable TOTP Token Enrollment)

@nilsbehlen

**Comment by nilsbehlen** [comment]
Hi, 
try this unofficial pre-release:
[PrivacyIDEA-ADFS-Provider-v1.0.2-pre.msi.zip](https://github.com/privacyidea/adfs-provider/files/8861530/PrivacyIDEA-ADFS-Provider-v1.0.2-pre.msi.zip)
please report back if you encounter any problems with the feature.

**Comment by arpsyapathy** [comment]
> Hi, try this unofficial pre-release: [PrivacyIDEA-ADFS-Provider-v1.0.2-pre.msi.zip](https://github.com/privacyidea/adfs-provider/files/8861530/PrivacyIDEA-ADFS-Provider-v1.0.2-pre.msi.zip) please report back if you encounter any problems with the feature.

Hi @nilsbehlen 

Thats worked! Thank you!

Can I somehow change the text on the QR page?

**Comment by nilsbehlen** [comment]
currently you can only modify the section where the apps are shown. The registry key is `enrollment_apps` and for the value you can write HTML formatted text (this is a potential security issue, need to make an issue for that).

**Comment by arpsyapathy** [comment]
> currently you can only modify the section where the apps are shown. The registry key is `enrollment_apps` and for the value you can write HTML formatted text (this is a potential security issue, need to make an issue for that #19 ).

@nilsbehlen 
Sadly. This would be a great feature. Because there is a need to translate the page into my language.
